"""
Django settings for data_center project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z6cufq0k-@p7(c6&%4o4)l6#me2kd*9x-drh-iwh$ki2_db)q0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'cona',
    'kamba',
    'common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True   #允许携带cookie
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = ( '*')  #跨域增加忽略
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'VIEW', )

#允许的请求头
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
 )

ROOT_URLCONF = 'data_center.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'data_center.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE = {
    "Windows": {
        "host": "localhost",
        "user": "root",
        "password": "299521",
        "database": "data_center_statistical"
    },
    "Linux": {
        "host": "121.199.48.82",
        "user": "root",
        "password": "cdqr2008",
        "database": "data_center_statistical"
    }
}

POINT_DF = {"时间列 1": "Timestamp", "板换1/2串联调节阀,开度反馈AEV-0211": "HX1_2_AEV_0211 ", "开度反馈DEV-1001": "DEV-1001", "锅炉-1,温度": "BL001_HHWTemp", "锅炉-2,温度": "BL002_HHWTemp", "锅炉-3,温度": "BL003_HHWTemp", "锅炉-4,温度": "BL004_HHWTemp", "流量FM-0201": "SolarRFM_0201", "蓄热水池补水流量计:流量": "Pit_MU_flow", "管网回水主管,流量": "HHWLoop_RFlow", "集水器旁通管,流量": "HHWLoop_BypassFlow", "供热端补水FM-0801": "HHWLoop_MUflow", "太阳能侧补水,流量": "Solar_MUflow", "10-1:泵频率反馈": "SolarHCP101_HZ", "10-2:泵频率反馈": "SolarHCP102_HZ", "10-3:泵频率反馈": "SolarHCP103_HZ", "10-4:泵频率反馈": "SolarHCP104_HZ", "2-1,频率反馈": "HHWPP201_HZ", "2-2,频率反馈": "HHWPP202_HZ", "2-3,频率反馈": "HHWPP203_HZ", "1-1,频率反馈": "HHWPP101_HZ", "1-2,频率反馈": "HHWPP102_HZ", "1-3,频率反馈": "HHWPP103_HZ", "1-4,频率反馈": "HHWPP104_HZ", "1-5,频率反馈": "HHWPP105_HZ", "1-6,频率反馈": "HHWPP106_HZ", "1-7,频率反馈": "HHWPP107_HZ", "管网回水主管,温度TE-0702": "HHWLoop_RT", "管网供水主管,温度TE-0701": "HHWLoop_ST", "4-1:泵频率反馈": "HHWSP401_HZ", "4-2:泵频率反馈": "HHWSP402_HZ", "4-3:泵频率反馈": "HHWSP403_HZ", "4-4:泵频率反馈": "HHWSP404_HZ", "板换1-1二次侧出口,温度TE-0401": "Pit_DisH_HX101_SLT", "板换1-2二次侧出口,温度TE-0402": "Pit_DisH_HX102_SLT", "板换3总管,二次侧出口,温度TE-0237": "Pit_Charge_HX103_106_SLT", "8-1:泵频率反馈": "Pit_ChargeP801_HZ", "8-2:泵频率反馈": "Pit_ChargeP802_HZ", "8-3:泵频率反馈": "Pit_ChargeP803_HZ", "5-1:泵频率反馈": "Pit_DisP501_HZ", "5-2:泵频率反馈": "Pit_DisP502_HZ", "5-3:泵频率反馈": "Pit_DisP503_HZ", "水池低位温度T1": "Pit_LT01_0m00cm", "水池低位温度T2": "Pit_LT02_0m20cm", "水池低位温度T3": "Pit_LT03_0m40cm", "水池低位温度T4": "Pit_LT04_0m60cm", "水池低位温度T5": "Pit_LT05_0m80cm", "水池低位温度T6": "Pit_LT06_1m00cm", "水池低位温度T7": "Pit_LT07_1m20cm", "水池低位温度T8": "Pit_LT08_1m40cm", "水池低位温度T9": "Pit_LT09_1m60cm", "水池低位温度T10": "Pit_LT10_1m80cm", "水池低位温度T11": "Pit_LT11_2m00cm", "水池低位温度T12": "Pit_LT12_2m20cm", "水池低位温度T13": "Pit_LT13_2m40cm", "水池低位温度T14": "Pit_LT14_2m60cm", "水池低位温度T15": "Pit_LT15_2m80cm", "水池低位温度T16": "Pit_LT16_3m00cm", "水池低位温度1": "Pit_LT01_0m00cm", "水池低位温度2": "Pit_LT02_0m20cm", "水池低位温度3": "Pit_LT03_0m40cm", "水池低位温度4": "Pit_LT04_0m60cm", "水池低位温度5": "Pit_LT05_0m80cm", "水池低位温度6": "Pit_LT06_1m00cm", "水池低位温度7": "Pit_LT07_1m20cm", "水池低位温度8": "Pit_LT08_1m40cm", "水池低位温度9": "Pit_LT09_1m60cm", "水池低位温度10": "Pit_LT10_1m80cm", "水池低位温度11": "Pit_LT11_2m00cm", "水池低位温度12": "Pit_LT12_2m20cm", "水池低位温度13": "Pit_LT13_2m40cm", "水池低位温度14": "Pit_LT14_2m60cm", "水池低位温度15": "Pit_LT15_2m80cm", "水池低位温度16": "Pit_LT16_3m00cm", "水池中位温度T1": "Pit_MT01_3m20cm", "水池中位温度T2": "Pit_MT02_3m40cm", "水池中位温度T3": "Pit_MT03_3m60cm", "水池中位温度T4": "Pit_MT04_3m80cm", "水池中位温度T5": "Pit_MT05_4m00cm", "水池中位温度T6": "Pit_MT06_4m20cm", "水池中位温度T7": "Pit_MT07_4m40cm", "水池中位温度T8": "Pit_MT08_4m60cm", "水池中位温度T9": "Pit_MT09_4m80cm", "水池中位温度T10": "Pit_MT10_5m00cm", "水池中位温度T11": "Pit_MT11_5m20cm", "水池中位温度T12": "Pit_MT12_5m40cm", "水池高位温度T1": "Pit_HT01_5m73cm", "水池高位温度T2": "Pit_HT02_6m06cm", "水池高位温度T3": "Pit_HT03_6m39cm", "水池高位温度T4": "Pit_HT04_6m72cm", "水池高位温度T5": "Pit_HT05_7m05cm", "水池高位温度T6": "Pit_HT06_7m38cm", "水池高位温度T7": "Pit_HT07_7m71cm", "水池高位温度T8": "Pit_HT08_8m04cm", "水池高位温度T9": "Pit_HT09_8m37cm", "水池高位温度T10": "Pit_HT10_8m70cm", "水池高位温度T11": "Pit_HT11_9m03cm", "水池高位温度T12": "Pit_HT12_9m36cm", "水池液位:液位1": "Pit_W_level1", "水池液位:液位2": "Pit_W_level2", "蓄热水池底部,PH值": "Pit_L_PH", "蓄热水池中部,PH值": "Pit_M_PH", "蓄热水池顶部,PH值": "Pit_H_PH", "冷却塔集水盘水位:液位": "CT_W_level", "冷却塔回水温度传感器:温度TE-0901": "CT_CWLT", "冷凝器侧补水,压力": "Cond_MU_P", "蒸发器侧补水,压力": "Evap_MU_P", "太阳能侧补水,压力": "Solar_MU_P", "回水主管,压力P-0804": "HHWLoop_RP", "集水器,压力": "HHWLoop_R_COM_P", "集水器,温度": "HHWLoop_R_COM_T", "太阳能矩阵供水总管，温度TE-049": "SolarHWLoop_ST", "太阳能矩阵回水总管，温度TE-050": "SolarHWLoop_RT", "矩阵内平均温度": "SolarPT_Ave", "SEHCM01-板内温度传感器1": "SolarPT1_SEHCM01", "SEHCM01-板内温度传感器2": "SolarPT2_SEHCM01", "SEHCM01-板内温度传感器3": "SolarPT3_SEHCM01", "SEHCM01-板内温度传感器4": "SolarPT4_SEHCM01", "SEHCM01-板内温度传感器5": "SolarPT5_SEHCM01", "SEHCM01-矩阵主管进口温度传感器": "SolarInletT__SEHCM01", "SEHCM01-矩阵主管出口温度传感器": "SolarOutletT__SEHCM01", "SEHCM02-板内温度1": "SolarPT1_SEHCM02", "SEHCM02-板内温度2": "SolarPT2_SEHCM02", "SEHCM02-板内温度3": "SolarPT3_SEHCM02", "SEHCM02-板内温度4": "SolarPT4_SEHCM02", "SEHCM02-板内温度5": "SolarPT5_SEHCM02", "SEHCM02-进口温度": "SolarInletT__SEHCM02", "SEHCM02-出口温度": "SolarOutletT__SEHCM02", "SEHCM03-板内温度1": "SolarPT1_SEHCM03", "SEHCM03-板内温度2": "SolarPT2_SEHCM03", "SEHCM03-板内温度3": "SolarPT3_SEHCM03", "SEHCM03-板内温度4": "SolarPT4_SEHCM03", "SEHCM03-板内温度5": "SolarPT5_SEHCM03", "SEHCM03-进口温度": "SolarInletT__SEHCM03", "SEHCM03-出口温度": "SolarOutletT__SEHCM03", "SEHCM04-板内温度1": "SolarPT1_SEHCM04", "SEHCM04-板内温度2": "SolarPT2_SEHCM04", "SEHCM04-板内温度3": "SolarPT3_SEHCM04", "SEHCM04-板内温度4": "SolarPT4_SEHCM04", "SEHCM04-板内温度5": "SolarPT5_SEHCM04", "SEHCM04-进口温度": "SolarInletT__SEHCM04", "SEHCM04-出口温度": "SolarOutletT__SEHCM04", "SEHCM05-板内温度1": "SolarPT1_SEHCM05", "SEHCM05-板内温度2": "SolarPT2_SEHCM05", "SEHCM05-板内温度3": "SolarPT3_SEHCM05", "SEHCM05-板内温度4": "SolarPT4_SEHCM05", "SEHCM05-板内温度5": "SolarPT5_SEHCM05", "SEHCM05-进口温度": "SolarInletT__SEHCM05", "SEHCM05-出口温度": "SolarOutletT__SEHCM05", "SEHCM06-板内温度1": "SolarPT1_SEHCM06", "SEHCM06-板内温度2": "SolarPT2_SEHCM06", "SEHCM06-板内温度3": "SolarPT3_SEHCM06", "SEHCM06-板内温度4": "SolarPT4_SEHCM06", "SEHCM06-板内温度5": "SolarPT5_SEHCM06", "SEHCM06-进口温度": "SolarInletT__SEHCM06", "SEHCM06-出口温度": "SolarOutletT__SEHCM06", "SEHCM07-板内温度1": "SolarPT1_SEHCM07", "SEHCM07-板内温度2": "SolarPT2_SEHCM07", "SEHCM07-板内温度3": "SolarPT3_SEHCM07", "SEHCM07-板内温度4": "SolarPT4_SEHCM07", "SEHCM07-板内温度5": "SolarPT5_SEHCM07", "SEHCM07-进口温度": "SolarInletT__SEHCM07", "SEHCM07-出口温度": "SolarOutletT__SEHCM07", "SEHCM08-板内温度1": "SolarPT1_SEHCM08", "SEHCM08-板内温度2": "SolarPT2_SEHCM08", "SEHCM08-板内温度3": "SolarPT3_SEHCM08", "SEHCM08-板内温度4": "SolarPT4_SEHCM08", "SEHCM08-板内温度5": "SolarPT5_SEHCM08", "SEHCM08-进口温度": "SolarInletT__SEHCM08", "SEHCM08-出口温度": "SolarOutletT__SEHCM08", "软化水箱,液位": "SoftWTank_Level", "容积式换热水箱,生活热水,温度": "DHWT", "容积式换热水箱,水箱内,温度": "DHW_Tank_T", "生活高位水位:液位": "DHW_Tank_Level", "消防水池水位:液位": "Fire_Tank_Level", "板换2总管,二次侧出口,温度": "Pit_DisL_HX201_206_SLT", "板换1总管,一次侧出口,温度": "Pit_DisH_HX101_102_PLT", "板换2总管,一次侧出口,温度": "Pit_DisL_HX201_206_PLT", "水源热泵-1蒸发器进口,温度TE-0507": "WSHP001_CHWET", "水源热泵-1蒸发器出口,温度TE-0508": "WSHP001_CHWLT", "水源热泵-1冷凝器出口,流量": "WSHP001_HHWF", "水源热泵-1冷凝器进口,温度TE-0601": "WSHP001_HHWET", "水源热泵-1冷凝器出口,温度TE-0602": "WSHP001_HHWLT", "水源热泵-2蒸发器进口,温度TE-0509": "WSHP002_CHWET", "水源热泵-2蒸发器出口,温度TE-0510": "WSHP002_CHWLT", "水源热泵-2冷凝器出口,流量": "WSHP002_HHWF", "水源热泵-2冷凝器进口,温度TE-0603": "WSHP002_HHWET", "水源热泵-2冷凝器出口,温度TE-0604": "WSHP002_HHWLT", "水源热泵-3蒸发器进口,温度TE-0511": "WSHP003_CHWET", "水源热泵-3蒸发器出口,温度TE-0512": "WSHP003_CHWLT", "水源热泵-3冷凝器出口,流量": "WSHP003_HHWF", "水源热泵-3冷凝器进口,温度TE-0605": "WSHP003_HHWET", "水源热泵-3冷凝器出口,温度TE-0606": "WSHP003_HHWLT", "水源热泵-4蒸发器进口,温度TE-0513": "WSHP004_CHWET", "水源热泵-4蒸发器出口,温度TE-0514": "WSHP004_CHWLT", "水源热泵-4冷凝器出口,流量": "WSHP004_HHWF", "水源热泵-4冷凝器进口,温度TE-0607": "WSHP004_HHWET", "水源热泵-4冷凝器出口,温度TE-0608": "WSHP004_HHWLT", "水源热泵-5蒸发器进口,温度TE-0515": "WSHP005_CHWET", "水源热泵-5蒸发器出口,温度TE-0516": "WSHP005_CHWLT", "水源热泵-5冷凝器出口,流量": "WSHP005_HHWF", "水源热泵-5冷凝器进口,温度TE-0609": "WSHP005_HHWET", "水源热泵-5冷凝器出口,温度TE-0610": "WSHP005_HHWLT", "水源热泵-6蒸发器进口,温度TE-0517": "WSHP006_CHWET", "水源热泵-6蒸发器出口,温度TE-0518": "WSHP006_CHWLT", "水源热泵-6冷凝器出口,流量": "WSHP006_HHWF", "水源热泵-6冷凝器进口,温度TE-0611": "WSHP006_HHWET", "水源热泵-6冷凝器出口,温度TE-0612": "WSHP006_HHWLT", "气压": "Barometric", "温度": "OAT", "湿度": "RH", "辐射量": "SolarE", "辐射功率": "SolarW", "水源热泵冷凝侧1-1电度量": "HHWPP101KWH", "水源热泵冷凝侧1-2电度量": "HHWPP102KWH", "水源热泵冷凝侧1-3电度量": "HHWPP103KWH", "水源热泵冷凝侧1-4电度量": "HHWPP104KWH", "水源热泵冷凝侧1-5电度量": "HHWPP105KWH", "水源热泵冷凝侧1-6电度量": "HHWPP106KWH", "水源热泵冷凝侧1-7电度量": "HHWPP107KWH", "水源热泵蒸发侧3-1电度量": "CHWP301KWH", "水源热泵蒸发侧3-2电度量": "CHWP302KWH", "水源热泵蒸发侧3-3电度量": "CHWP303KWH", "水源热泵蒸发侧3-4电度量": "CHWP304KWH", "水源热泵蒸发侧3-5电度量": "CHWP305KWH", "水源热泵蒸发侧3-6电度量": "CHWP306KWH", "水源热泵蒸发侧3-7电度量": "CHWP307KWH", "供热主泵4-1电度量": "SHHWP401KWH", "供热主泵4-2电度量": "SHHWP402KWH", "供热主泵4-3电度量": "SHHWP403KWH", "供热主泵4-4电度量": "SHHWP404KWH", "循环泵10-1电度量": "SolarHCP101KWH", "循环泵10-2电度量": "SolarHCP102KWH", "循环泵10-3电度量": "SolarHCP103KWH", "循环泵10-4电度量": "SolarHCP104KWH", "冷却塔循环14-1电度量": "CTPump141KWH", "冷却塔循环14-2电度量": "CTPump142KWH", "冷却塔循环14-3电度量": "CTPump143KWH", "蓄热水池放热5-1电度量": "Pit_DisP501KWH", "蓄热水池放热5-2电度量": "Pit_DisP502KWH", "蓄热水池放热5-3电度量": "Pit_DisP503KWH", "蓄热水池8-1电度量": "Pit_ChargeP801KWH", "蓄热水池8-2电度量": "Pit_ChargeP802KWH", "蓄热水池8-3电度量": "Pit_ChargeP803KWH", "高温板换冷凝侧2-1电度量": "HHWPP201KWH", "高温板换冷凝侧2-2电度量": "HHWPP202KWH", "高温板换冷凝侧2-3电度量": "HHWPP203KWH", "冷却塔风机1电度量": "CTF001KWH", "冷却塔风机2电度量": "CTF002KWH", "冷却塔风机3电度量": "CTF003KWH", "冷却塔风机4电量": "CTF004KWH", "供热侧补水6-1电量": "HHWLoopMUP601KWH", "供热侧补水6-2电量": "HHWLoopMUP602KWH", "太阳能矩阵补水12-2电量": "SolarMUP122KWH", "太阳能矩阵补水12-1电量": "SolarMUP121KWH", "冷却塔补水7-1电量": "CTMUP701KWH", "冷却塔补水7-2电量": "CTMUP702KWH", "软化水箱补水1电量": "SoftWMUP001KWH", "软化水箱补水2电量": "SoftWMUP002KWH", "蓄热水池补水13-2电量": "PitMUP132KWH", "蓄热水池补水13-1电量": "PitMUP131KWH", "水源热泵1电量": "WSHP001KWH", "水源热泵2电量": "WSHP002KWH", "水源热泵3电量": "WSHP003KWH", "水源热泵4电量": "WSHP004KWH", "水源热泵5电量": "WSHP005KWH", "水源热泵6电量": "WSHP006KWH", "湿球温度": "WB", "冷却塔环境温度": "CT_OAT", "水池高温层平均温度": "Pit_H_T", "水池中温层平均温度": "Pit_M_T", "水池低温层平均温度": "Pit_L_T", "CWP101频率": "CWP101_HZ", "CWP102频率": "CWP102_HZ", "CWP103频率": "CWP103_HZ", "LQ-T5温度": "CT_LT", "冷却塔风机1频率": "CTF001_HZ", "冷却塔风机2频率": "CTF002_HZ", "远端供水压力": "HHWSP", "远端回水压力": "HHWRP"}

